language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio update
script:
- mkdir build
- platformio ci --keep-build-dir --build-dir ./build --project-conf=platformio.ini
  src/*.cpp
before_deploy:
- platformio ci -h
- ls -a
- find . -name "*.bin"
deploy:
  provider: releases
  api_key:
    secure: fMZsOWaBH9lrRs8s81WrwIGpBHGddYSwcbFI2HU32EEALxEzTnw8xrUMXPVgaTQjrKwhMc/ToK5AOsZLpcpd+KTluGSH3vO+hbY0n8GcKbychATE+pT5lSx2v3HK5YbhGP1/YNthoYbVZ361pyUZ2YyHFVgt01DYEjNyvHo7iBOnM9aJm9mYGQ938FGoSAKjUGXM5Rrm+bcBQg9hdDB1LiPjAAbrr1H2mL0WulT4RErStRWcMvHgwQafmqAQnWRvAVcbYIJUL+6ZiAM9xZGTP7EMEVwwBAgsyrdM4aJcBBEBSjbrl//rFMelXg6UJDAxzJzM1+lCtXtSS63I4u97vSg9H2sR4wPXofT+lBozxrqTCyFiUHCTUhtmJcpwivfzLLea/eJhIgSKgtZDBKvlO+/AtKpAwpHSdBS6vAhWKnytcju7UQ3p9WOq+qn+nfLTFCQcqlG37LD/W3lnZnlEmZSHSf8NG4w8tEvl9jOsylEtlf5UcXt01OWJ7FbiwGAPvEXu5SQZCNK2HP9b4Q7M9+xJjpGSlmDRj4cA7zHZ3QdgMMP1iswbCmLGa6RhFAYMitoFdqtJaUZSxC53pX5LM4zXQnjBAmoDaC/4fDizNMMyVY832ddtr0j3PcQchrU5Sk0lMOj0pPd/Y4nvoRhapBLMSBsLeFo1JuLWqKYbHgk=
  file: ''
  on:
    repo: IoTDevice/esp8266-gy-30
